### PR TITLE
Update README.md images

### PR DESCRIPTION
**Pull request by droffilc1**

### CODE REVIEW

**Review by simonprickett — APPROVED** [review]
Thanks @droffilc1 looks good! @SuzeShardlow good to merge!

**Comment by SuzeShardlow** [comment]
Thanks for your contribution, @droffilc1!  I will give you the `Hacktoberfest 2022` role in our Discord server :D

**Comment by droffilc1** [comment]
Thank you too for the opportunity

**Comment by SuzeShardlow** [comment]
I just realised what "droffilc" means! 😀

**Pull request merged**
