### PR TITLE
Feature: Add Redisearch to Backend.

### LINKED ISSUE #11: Enhance the application backend with RediSearch
This application stores its station data in two places... a Redis geo key containing all stations, and a series of Redis Hashes - one for each station.  Currently, the application does nothing with the data in the Hashes whose keys are of the form `station:<stationName>`.

Here's Ashby for example:

```bash
127.0.0.1:6379> hgetall station:ashby
 1) "altitudeMode"
 2) "clampToGround"
 3) "City"
 4) "Berkeley"
 5) "AssetType"
 6) "Station"
 7) "Long"
 8) "-122.269981"
 9) "Street"
10) "3100 Adeline Street"
11) "FID"
12) "45"
13) "Lat"
14) "37.85257"
15) "Field_1"
16) "Ashby"
```

Update the application to use RediSearch as follows:

* Change the Redis container used in `docker-compose.yml` from the current `redis:6.2.1-alpine` image to instead use the latest RediSearch container: https://hub.docker.com/r/redislabs/redisearch
* Add code to create a RediSearch index in `load_stations.py`.  Give your index the name `idx:stations` - you'll need to index the City field of hashes whose keys begin with the prefix `station:*`.  Use the RediSearch library for this https://pypi.org/project/redisearch/ (note you are working with RediSearch 2 here)
* Add a new route in `app.py`: 

```python
@app.route("/api/search/bycity/<city_name>")
def search_by_city_name(city_name):
  # TODO code here...
```

* This route should:
  *  Use RediSearch and your search index that you created in `load_stations.py` to find all stations where the "City" field has the value "<city_name>"
  *  Return an array of JSON objects that looks like this for each match:

```json
[
  {
    "name": "<station name>",
    "city": "<station city>",
    "location": {
        "latitude": <station latitude>,
        "longitude": <station longitude>
    }
  }
]
```  

* When sending RediSearch commands to Redis, use the redisearch library to make your search queries (see examples here https://github.com/simonprickett/introducing-redis-talk/tree/main/full_text_search_and_secondary_indexing)

* Test your route by calling `GET localhost:8080/api/search/bycity/Oakland` and `GET localhost:8080/api/search/bycity/San Francisco`

* Make sure that the existing front end maps search functionality still works :)

* Make sure you updated `requirements.txt` with the new redisearch library dependency.

This is part of our participation in Hacktoberfest 2021. Learn how to complete this issue here: https://developer.redis.com/hacktoberfest/

Need help or want to talk to us? Join us on Discord where we have a dedicated Hacktoberfest channel: https://discord.gg/ueQwKUh5Z3

### PR DESCRIPTION
**Pull request by teezzan**
This closes #11. ~It is a work in progress.~ My Twitter handle is @TaiwoHW  and my discord handle is Taiwo#7119.

### CODE REVIEW

**Comment by teezzan** [comment]
@simonprickett Here is the [piece](https://github.com/redis-developer/introducing-the-geosearch-command/blob/876a611a1403ed72acef490aad13dc8f23000367/load_stations.py#L17) that is problematic for me. It seems like in [redisearch-py](https://github.com/RediSearch/redisearch-py), the [`create_index` method](https://github.com/RediSearch/redisearch-py/blob/5d277a286f2592e24e721cba260ee6d348b72d5a/redisearch/client.py#L264) of the client takes a `field` and  I am stumped by what the `field` should be in this case. Thank you

**Comment by simonprickett** [comment]
@teezzan Hi there, you should be able to use the sample code here to get started:

https://github.com/RediSearch/redisearch-py#defining-a-search-index

You'll want a schema definition that defines the City field as text as a minimum start point, and in your index definition, watch hashes beginning `station:`

**Comment by teezzan** [comment]
Thanks for your help @simonprickett. Here we go!

**Review by simonprickett — APPROVED** [review]
Looks great and works well, thank you!  We'll get this labelled and merged for Hacktoberfest for you!

**Review by SuzeShardlow — APPROVED** [review]
Thanks @teezzan!  I will add the label and merge this :)

**Comment by SuzeShardlow** [comment]
Thanks, @teezzan!  If you are a member of our Discord (https://discord.com/invite/ueQwKUh5Z3), please drop your handle here and we will give you the Hacktoberfest 2021 role :) and if you'd like a shout out on Twitter, drop your handle!

**Pull request merged**
